// <auto-generated />
using FinanceAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceAPI.Migrations
{
    [DbContext(typeof(FinanceAPIContext))]
    partial class FinanceAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FinanceAPI.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GDP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });


            modelBuilder.Entity("FinanceAPI.Models.Economy", b =>
                {
                    b.Property<int>("EconomyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("GDP")
                        .HasColumnType("double");

                    b.Property<double>("InflationRate")
                        .HasColumnType("double");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double");

                    b.Property<double>("UnemplRate")
                        .HasColumnType("double");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("EconomyId");

                    b.ToTable("Economy");

            modelBuilder.Entity("FinanceAPI.Models.Pitcher", b =>
                {
                    b.Property<int>("PitcherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Pitches")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("PitcherId");

                    b.ToTable("Pitchers");
                    
                });
#pragma warning restore 612, 618
        }
    }
}
